-- Illogical Impulse ISO — Material You colours for Neovim (#26 / PROPOSAL §9).
--
-- GENERATED by ii-theme-feeder.sh (matugen json <colors.json> --config
-- ~/.config/illogical-impulse-theming/config.toml). Do NOT edit by hand — every
-- wallpaper/flavor change regenerates it. The placeholders are filled from
-- upstream's FINISHED colours.json (flat name to hex map), so these track the
-- exact rice palette.
--
-- Usage (opt-in): from your own nvim config,
--     local ok, ii = pcall(require, "ii-material")
--     if ok then  -- ii.primary, ii.background, … are "#rrggbb" strings
--       vim.api.nvim_set_hl(0, "Normal", { fg = ii.on_background, bg = ii.background })
--     end
-- Nothing forces this module on nvim; deleting it (or disabling the feeder) is a
-- clean no-op.

return {
  background        = "{{background}}",
  on_background     = "{{on_background}}",
  surface           = "{{surface}}",
  on_surface        = "{{on_surface}}",
  surface_variant   = "{{surface_variant}}",
  on_surface_variant = "{{on_surface_variant}}",
  primary           = "{{primary}}",
  on_primary        = "{{on_primary}}",
  primary_container = "{{primary_container}}",
  secondary         = "{{secondary}}",
  tertiary          = "{{tertiary}}",
  error             = "{{error}}",
  outline           = "{{outline}}",
}
