# shellcheck shell=bash disable=SC2154
# 60-boot — live systemd-boot menu + regenerate profiledef.sh.
#
# Identity fields come from distro.toml; everything else (compression,
# image type, buildmodes) is inherited from the releng profiledef — those
# are the parts you do NOT want to fight upstream on.

step "overlay/efiboot → build/efiboot"
rm -rf "$BUILD/efiboot/loader/entries"
rsync -a "$OVERLAY/efiboot/" "$BUILD/efiboot/"
ok "$(ls "$BUILD/efiboot/loader/entries/" | wc -l) loader entries"

step "profiledef.sh (identity from distro.toml)"
_pd_name="$(tget iso.name_prefix)"
_pd_label="$(tget iso.label_prefix)_$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y%m)"
_pd_publisher="$(tget distro.publisher)"
_pd_application="$(tget distro.application)"
(
  set +u
  declare -A file_permissions
  declare -a bootmodes buildmodes airootfs_image_tool_options bootstrap_tarball_compression
  # shellcheck disable=SC1091
  source "$BUILD/profiledef.sh"

  iso_name="$_pd_name"
  iso_label="$_pd_label"
  iso_publisher="$_pd_publisher"
  iso_application="$_pd_application"
  iso_version="$ISO_VERSION"
  # UEFI-only, matching the installed system (GPT + systemd-boot).
  bootmodes=('uefi.systemd-boot')

  # Permissions for files we add on top of releng. Every path must exist in
  # airootfs/ or mkarchiso aborts (checked below).
  declare -A extra_file_permissions=(
    ["/etc/sudoers.d/10-wheel-nopasswd"]="0:0:0440"
    ["/etc/greetd/config.toml"]="0:0:0644"
    ["/etc/greetd/config.toml.installed.template"]="0:0:0644"
    ["/root/aur-packages.txt"]="0:0:0644"
    ["/usr/local/lib/ii/session-offline.sh"]="0:0:0644"
    ["/usr/local/bin/ii-session"]="0:0:0755"
    ["/usr/local/bin/ii-launch-installer"]="0:0:0755"
    ["/usr/local/bin/ii-live-welcome"]="0:0:0755"
    ["/usr/local/bin/ii-post-install"]="0:0:0755"
    ["/usr/local/bin/ii-prepare-bootloader"]="0:0:0755"
    ["/usr/local/bin/ii-finish-systemd-boot"]="0:0:0755"
    ["/usr/local/bin/ii-verify"]="0:0:0755"
    ["/usr/local/bin/ii-ensure-venv"]="0:0:0755"
    ["/usr/local/bin/ii-build-wheelhouse"]="0:0:0755"
    ["/usr/local/bin/iictl"]="0:0:0755"
    ["/root/nvidia-official.txt"]="0:0:0644"
    ["/root/nvidia-aur.txt"]="0:0:0644"
  )
  for k in "${!extra_file_permissions[@]}"; do
    file_permissions["$k"]="${extra_file_permissions[$k]}"
  done

  {
    echo "#!/usr/bin/env bash"
    echo "# AUTO-GENERATED by prepare.d/60-boot.sh — edit distro.toml and re-run prepare"
    echo "# shellcheck disable=SC2034"
    printf 'iso_name=%q\n'            "$iso_name"
    printf 'iso_label=%q\n'           "$iso_label"
    printf 'iso_publisher=%q\n'       "$iso_publisher"
    printf 'iso_application=%q\n'     "$iso_application"
    printf 'iso_version=%q\n'         "$iso_version"
    printf 'install_dir=%q\n'         "$install_dir"
    printf 'arch=%q\n'                "$arch"
    printf 'pacman_conf=%q\n'         "$pacman_conf"
    printf 'airootfs_image_type=%q\n' "$airootfs_image_type"
    printf 'bootmodes=( ';  for b in "${bootmodes[@]}";  do printf '%q ' "$b"; done; printf ')\n'
    printf 'buildmodes=( '; for b in "${buildmodes[@]}"; do printf '%q ' "$b"; done; printf ')\n'
    printf 'airootfs_image_tool_options=( '
    for o in "${airootfs_image_tool_options[@]}"; do printf '%q ' "$o"; done; printf ')\n'
    printf 'bootstrap_tarball_compression=( '
    for o in "${bootstrap_tarball_compression[@]}"; do printf '%q ' "$o"; done; printf ')\n'
    echo "file_permissions=("
    for k in "${!file_permissions[@]}"; do
      printf '  [%q]=%q\n' "$k" "${file_permissions[$k]}"
    done
    echo ")"
  } > "$BUILD/profiledef.sh.new"
  mv "$BUILD/profiledef.sh.new" "$BUILD/profiledef.sh"
)

# Every key in file_permissions[] must exist in airootfs/, else mkarchiso aborts.
_pd_dangling=0
while IFS= read -r p; do
  [[ -e "$BUILD/airootfs$p" ]] || { warn "dangling file_permissions[]: $p"; _pd_dangling=$((_pd_dangling + 1)); }
done < <(grep '^  \[' "$BUILD/profiledef.sh" | sed -E 's/^  \["?([^"]*)"?\]=.*/\1/')
(( _pd_dangling == 0 )) || die "$_pd_dangling dangling file_permissions paths — fix prepare.d/60-boot.sh"
ok "regenerated ($ISO_VERSION)"
