# config.nu — Illogical Impulse distro default for nushell.
#
# Copied by `iictl shell set nushell` into the UNOWNED ~/.config/nushell/config.nu
# IF absent. nushell CANNOT `cat` raw terminal escape sequences the way fish/zsh
# do, so `iictl shell set nushell` runs a translator that reads the EXACT
# upstream-generated ~/.local/state/quickshell/user/generated/terminal/sequences.txt
# and writes a nu-native theme to ~/.config/nushell/ii-material.nu; this config
# sources that theme (guarded) and inits starship. Re-run `iictl shell theme
# nushell` after a wallpaper change to refresh the palette. Fully reversible:
# delete these files → nushell's stock behaviour. Writes no upstream-owned path;
# contains no identity/PII.

# Sensible interactive defaults (do not override a value the user set later).
$env.config = {
    show_banner: false
    edit_mode: emacs
}

# ── Material You palette (nu-native, generated by the sequences→nu translator) ─
# Guarded source of the distro-owned translated theme. Absent (pre-first-boot or
# before `iictl shell set nushell`) → no-op, stock colors.
const ii_material = ($nu.home-path | path join ".config" "nushell" "ii-material.nu")
source ($ii_material)

# ── Prompt (starship, guarded) ────────────────────────────────────────────────
# starship supports nushell natively; the init file is generated once by
# `iictl shell set nushell`. Guard the source so an absent file is inert.
const ii_starship = ($nu.home-path | path join ".config" "nushell" "ii-starship.nu")
source ($ii_starship)
